// Code generated by tygo. DO NOT EDIT.

//////////
// source: environments.go

export interface Environment {
  id?: string;
  name?: string;
  /**
   * Services names in this environment by id
   */
  services?: { [key: string]: string};
  /**
   * Status pages names in this environment by id
   */
  statusPages?: { [key: string]: string};
}

//////////
// source: status-info.go

export interface ServiceComponent {
  status: Status;
  name: string;
  info: string;
}
export interface Service {
  id: string;
  name: string;
  status: Status;
  lastUpdate: number /* int64 */;
  serviceComponents: ServiceComponent[];
}
export interface StatusInfo {
  lastUpdate: number /* int64 */;
  overallStatus: Status;
  services: Service[];
  name: string;
}

//////////
// source: status.go

export type Status = number /* int64 */;
export const Unknown: Status = 0;
export const OK: Status = 1;
export const Info: Status = 2;
export const Warning: Status = 3;
export const Critical: Status = 4;
