// Code generated by tygo. DO NOT EDIT.

//////////
// source: status-info.go

export interface Service {
  id: string;
  name: string;
  status: Status;
  lastUpdate: number /* int64 */;
}
export interface StatusInfo {
  lastUpdate: number /* int64 */;
  statusPage: StatusPage;
  overallStatus: Status;
  services: Service[];
}

//////////
// source: status-page.go

export interface StatusPage {
  id?: string;
  name?: string;
}

//////////
// source: status.go

export type Status = number /* int64 */;
export const Unknown: Status = 0;
export const OK: Status = 1;
export const Warning: Status = 2;
export const Critical: Status = 3;
