## This config map describes a sample configuration for our status page
apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-queries
  labels:
    katastasi.io: "queries"
data:
  unhealthy_pods: 'sum (kube_pod_status_ready{condition="false" namespace="${namespace}"})'
  unhealthy_pods_for_deployment: 'sum (kube_pod_status_ready{condition="false", namespace="${namespace}", deployment="${deployment}"})'
  unhealthy_pods_for_statefulset: 'sum (kube_pod_status_ready{condition="false", namespace="${namespace}", statefulset="${statefulset}"})'
  consumergroup_lag: 'sum (kafka_consumergroup_lag{consumergroup="${consumergroup}"})'
  consumergroup_lag_for_topic: 'sum (kafka_consumergroup_lag{consumergroup="${consumergroup}", topic="${topic}"})'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-queries-duplicate
  labels:
    katastasi.io: "queries"
data:
  unhealthy_pods: 'sum (kube_pod_status_ready{condition="false" namespace="${namespace}"})'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-config
  labels:
    katastasi.io: "page"
  annotations:
    katastasi.io/page-id: "petshop"
    katastasi.io/name: "PetShop"
    katassisi.io/env: "production"
data:
  services: petshop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-config-fail
  labels:
    katastasi.io: "page"
  annotations:
    katastasi.io/page-id: "petshop-fail"
    katastasi.io/name: "PetShop no service"
    katassisi.io/env: "test"
data:
  services: petshop,petshop2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  labels:
    katastasi.io: "service"
  annotations:
    katastasi.io/service-id: "petshop"
    katastasi.io/name: "PetShop Service"
    katastasi.io/owner: "team-pet"
    katastasi.io/contact: "https://petshop.com/contact"
    katastasi.io/url: "https://petshop.com"
    katassisi.io/env: "production"
data:
  components: |
    - name: "Availability Pods"
      query: "unhealthy_pods"
      description: "There are unhealthy pods in the environment"
      conditions:
        - severity: "warning"
          condition: "gt"
          threshold: "0"
        - severity: "critical"
          condition: "gt"
          threshold: "0"
          duration: "5m"
    - name: "Consumer Group Lag"
      query: "consumergroup_lag"
      description: "There is consumer group lag in the environment"
      parameters:
        consumergroup: "petshop.*"
      conditions:
        - severity: "info"
          condition: "gt"
          threshold: "0"
          on: "raising"
        - severity: "warning"
          condition: "gt"
          threshold: "0"
          on: "raising"
        - severity: "critical"
          condition: "gt"
          threshold: "1000"
          on: "raising"
    - name: "Availability Pods for deployment"
      query: "unhealthy_pods_for_deployment"
      description: "There are unhealthy pods in the deployment"
      parameters:
        deployment: "petshop.*"
      conditions:
        - severity: "warning"
          condition: "gt"
          threshold: "0"
        - severity: "critical"
          condition: "gt"
          threshold: "0"
          duration: "5m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config-fail
  labels:
    katastasi.io: "service"
data:
  components: |
    - name: "Availability Pods"
      queritical"
            condition: "gt"
            threshold: "0"
            duration: "5m"

