name: main

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: "current"
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: npm install
        run: npm ci
        working-directory: ui

      - name: build frontend
        run: npm run build
        working-directory: ui

      - name: go mod tidy
        run: go mod tidy

      - name: run go tests
        run: go test ./pkg/...

      - name: run go generate
        run: go generate ./ui

      - name: install browsers
        run: npx playwright install

      - name: run npm tests
        run: npm run test:e2e
        working-directory: ui

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Showing difference
        run: git --no-pager diff
      - name: Checking for differences
        run: git diff-index --exit-code HEAD --

